// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgomwmpgjfaumneehcel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnb213bXBnamZhdW1uZWVoY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzUwNzEsImV4cCI6MjA2NTQxMTA3MX0.JVRwDiLJVvfACZgDZXuFGiZVS_IvOrmNomzsmYXlVe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);